blank_issues_enabled: true
contact_links:
  - name: Questions / Support
    url: https://github.com/roblandry/apex-fusion-home-assistant/discussions
    about: Please use Discussions for questions and setup help.
